# Generated by Django 2.0.5 on 2018-05-19 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='goal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='goals.Goal'),
            preserve_default=False,
        ),
    ]
